import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import LogIn from './Components/LogIn'
import LogOut from './Components/LogOut'
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth]';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
 let seesion = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body>
      <div className='navbar'>
        <ul>
          <Link href="/list">
          <li>홈</li>
          </Link>
          </ul>
          <ul className='navbar-right'>
        <li>
          {
            seesion
            ? <span>{seesion.user.name}&nbsp; <LogOut /></span>
            : <span><LogIn /> <Link href={'/login'}> <span>/ 회원가입</span></Link> </span>
          }
        </li>
        <li>
          
         
        </li>
        </ul>
        </div>
      {children}</body>
    </html>
  )
}
