import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import LogIn from './Components/LogIn'
import LogOut from './Components/LogOut'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
 let seesion = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body>
      <div className='navbar'>
        <ul>
          <Link href="/list">
          <li>홈</li>
          </Link>
        <li>
          {
            seesion
            ? <span>{seesion.user.name}<LogOut /></span>
            : <LogIn></LogIn>
          }
        </li>
        </ul>
        </div>
      {children}</body>
    </html>
  )
}
